# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/<ROOT-FS>";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/<BOOT-FS>";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/.swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20u2.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };
  hardware.opengl = let 
    # Vulkan layers
    fn = oa: {
      nativeBuildInputs = oa.nativeBuildInputs ++ [pkgs.glslang];
      mesonFlags = oa.mesonFlags ++ ["-Dvulkan-layers=device-select,overlay"];
      postInstall = oa.postInstall + ''
        mv $out/lib/libVkLayer* $drivers/lib

        # Device select layer
        layer=VkLayer_MESA_device_select
        substituteInPlace $drivers/share/vulkan/implicit_layer.d/''${layer}.json \
          --replace "lib''${layer}" "$drivers/lib/lib''${layer}"

        # Overlay layer
        layer=VkLayer_MESA_overlay
        substituteInPlace $drivers/share/vulkan/explicit_layer.d/''${layer}.json \
          --replace "lib''${layer}" "$drivers/lib/lib''${layer}"
      '';
    };
  in with pkgs; {
    enable = true;
    driSupport32Bit = true;
    package = (mesa.overrideAttrs fn).drivers;
    package32 = (pkgsi686Linux.mesa.overrideAttrs fn).drivers;
    # Video acceleration for Intel iGPUs
    extraPackages = [
      intel-media-driver
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
}
