#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#2E3440"
bspc config focused_border_color "#434C5E"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set resolution
xrandr --output Virtual1 --mode 1920x1200 &

# Swap caps+escape
setxkbmap -option caps:swapescape &

# Wallpaper
nitrogen --set-zoom-fill ~/Pictures/Wallpapers/nord_astro.png &

# Bar
sh ~/.config/polybar/launch.sh --forest &

# Compositor
picom -f &
