#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-1 -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#4C566A"
bspc config normal_border_color "#3B4252"
bspc config active_border_color "#3B4252"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set resolution
xrandr --output HDMI-A-0 --mode 1920x1200 --rate 60.00 --output HDMI-A-1 --mode 1920x1200 --rate 60.00 &

# Swap caps+escape
setxkbmap -option caps:swapescape &

# Wallpaper
nitrogen --head=0 --set-zoom-fill ~/Pictures/Wallpapers/nord_astro.png &
nitrogen --head=1 --set-zoom-fill ~/Pictures/Wallpapers/nord_astro.png &

# Bar
sh ~/.config/polybar/launch.sh &

# Compositor
picom -f &

# Audio
pulseaudio --kill && pulseaudio &
mpd &

# Launch terminal on startup
alacritty &
