syntax enable
set hidden
set nowrap 
set encoding=utf-8
set fileencoding=utf-8
set ruler
set iskeyword+=-
set splitbelow
set splitright
set t_Co=256
set smarttab
set tabstop=4
set smartindent
set autoindent
set laststatus=0
set number
set relativenumber
set background=dark
set noshowmode
set nobackup
set nowritebackup
set updatetime=300
set timeoutlen=500
set formatoptions-=cro
set clipboard=unnamedplus
